import { motion } from 'framer-motion'
import { Link } from 'react-router-dom'
import { ActionLink, PageIntro, PublicShell, SectionLabel } from '../components/site/PagePrimitives'
import { missionScrapbook } from '../lib/missionScrapbook'
import { useCityPath } from '../lib/CityContext'

export function MissionPage() {
  const path = useCityPath()
  return <PublicShell><main>
    <PageIntro eyebrow="The reason we show up" title="A cleaner city starts with a clearer record." body="Ramani-Taka turns everyday observations into shared action. Report what is happening, make it easy for neighbours to respond, then keep the evidence open after the bags are gone." action={<div className="flex flex-wrap gap-3"><ActionLink to={path('/map')} tone="gold">See the field map</ActionLink><ActionLink to="/race" tone="light">Join the race</ActionLink></div>} />
    <section className="mx-auto max-w-7xl px-5 pb-20 sm:px-8 lg:px-12"><div className="grid gap-5 lg:grid-cols-[.8fr_1.2fr]">
      <div className="fn-panel-dark rounded-[2rem] bg-[#063b32] p-7 text-white sm:p-10"><SectionLabel>01 / Notice</SectionLabel><h2 className="fn-display mt-5 text-4xl font-extrabold tracking-[-.05em]">The first step is paying attention to a specific place.</h2><p className="mt-5 leading-7 text-teal-100/75">A photo, a location, and a little context are enough to make a street visible to the people who can help.</p><Link to={path('/map')} className="mt-8 inline-block font-bold text-gold-300">Open the map →</Link></div>
      <div className="grid gap-5 sm:grid-cols-2">{[['02','Bring the crew','Turn a pin into a plan with neighbours, cleanup teams, and local organisers.'],['03','Show the change','A cleared spot only counts when people can follow what happened next.']].map(([n,t,b])=><article key={n} className="rounded-[2rem] bg-white p-7 shadow-[var(--shadow-card)]"><span className="text-sm font-extrabold text-[#ef8268]">{n}</span><h3 className="fn-display mt-14 text-2xl font-extrabold tracking-[-.04em] text-[#063b32]">{t}</h3><p className="mt-3 leading-7 text-[#617972]">{b}</p></article>)}</div>
    </div></section>
    <section className="bg-[#e5f0eb] px-5 py-20 sm:px-8 lg:px-12"><div className="mx-auto max-w-7xl"><SectionLabel>Field notes</SectionLabel><div className="mt-8 columns-1 gap-5 sm:columns-2 lg:columns-3">{missionScrapbook.map((item,i)=><motion.article key={item.id} initial={{opacity:0,y:18}} whileInView={{opacity:1,y:0}} viewport={{once:true}} transition={{delay:i*.04}} className="mb-5 break-inside-avoid overflow-hidden rounded-[1.5rem] bg-[#fffdf7] shadow-[var(--shadow-card)]">{item.imageSrc&&<img src={item.imageSrc} alt="" className="aspect-[4/3] w-full object-cover" loading="lazy"/>}<div className="p-5"><p className="fn-eyebrow">{item.dateLabel}</p><h2 className="fn-display mt-2 text-xl font-extrabold text-[#063b32]">{item.title}</h2><p className="mt-2 text-sm leading-6 text-[#617972]">{item.body}</p>{item.href&&<Link to={item.external?'/mission':item.href} className="mt-4 inline-block text-sm font-extrabold text-[#0b8c76]">Open note →</Link>}</div></motion.article>)}</div></div></section>
    <section className="mx-auto max-w-7xl px-5 py-20 sm:px-8 lg:px-12"><div className="rounded-[2rem] bg-[#fbbf24] p-8 sm:p-12"><p className="fn-eyebrow text-[#063b32]">Your turn</p><h2 className="fn-display mt-4 max-w-2xl text-4xl font-extrabold tracking-[-.05em] text-[#063b32] sm:text-5xl">Put one place on the record.</h2><p className="mt-4 max-w-xl text-[#38574f]">The city gets better when the people who live here can see what needs doing and what changed.</p><div className="mt-7"><ActionLink to={path('/map')} tone="dark">Report a dirty spot</ActionLink></div></div></section>
  </main></PublicShell>
}
